### PR TITLE
Changed setup.py to work with the 1.1 version

### PR DESCRIPTION
**Pull request by stjoannou**
The package dharma.core was never included

### CODE REVIEW

**Comment by posidron** [comment]
Why did you close the pull request, this was actually a true bug. ;-)

**Comment by stjoannou** [comment]
I found more stuff that I wanted to fix ;-) My latest commit I think is much better than the one I submitted initially.

**Comment by posidron** [comment]
👍  Let me know when you are done - It's much appreciated. The care about packaging gets sadly always neglected too much by me.

**Comment by stjoannou** [comment]
The latest commit works fine with pip in Python 2 and Python 3 when run via command line. Also tested importing it as library in python 2 and worked fine.

**Comment by posidron** [comment]
Thank @stjoannou!

**Pull request merged**
